### PR TITLE
using file to identify injections

### PR DESCRIPTION
**Pull request by caseyjlaw**
Injections will be identified by MJD, DM, beam (with tunable tolerance). If identified, they are given a special name "<yymmdd>inj<n>", where <n> is name in injection file.
These events will not be sent as triggers, but they will be saved as json. No evidence in etcd or naming iteration.

### CODE REVIEW

**Review by liamconnor — COMMENTED** [review]
That all looks good to me. We still need code that writes to the injection file every time the injection etcd key has updated. Where do you think that should go?

**Comment by caseyjlaw** [comment]
T2 currently includes the `dsa_injection.py` script that writes details to `/home/ubuntu/injection_list.txt`. Is that what you mean? If so, then the injection service will keep that file up to date.
I think that also means we can remove the /mon/corr/injection key altogether, right? 

Finally, to actually use the T2-identified injections, we'll need filplot to interpret it. So that will also drop the reading of the /mon/corr/injection, but instead infer injections from the "inj" string in the name. Here's where I'm thinking of making the change:
https://github.com/dsa110/dsa110-T3/blob/development/dsaT3/filplot_funcs.py#L626

Does that all sound correct?

**Review by liamconnor — COMMENTED** [review]
But isn't /home/ubuntu/injection_list.txt saved locally on corr00? My problem before was communicating that to h23 in a smart way. Is there an rsync somewhere? 

Your changes to filplot_funcs look good, but will have to be tested.

**Comment by caseyjlaw** [comment]
If I understand correctly, only T2 needs to know about that file. Once identified, the candname inlcudes "inj". The T3 code on h23 can use that to identify the injections.
Do you think a special candname is all we need on h23?

**Pull request merged**
